#!/usr/bin/env bash
# .bash_profile

# Get the aliases and functions
if [ -f "$HOME/.bashrc" ]; then
    source "${HOME}/.bashrc"
fi

# User specific environment and startup programs

PATH="$PATH:$HOME/.local/bin:$HOME/bin:$GOPATH/bin"

export PATH
